
// Auto-generated enrichment: org + short description for 385 certifications
// Source: SarkariSetu Certification Directory (global reference)
export const ENRICHMENT = {
  "ActiveCampaign Certified": ["ActiveCampaign", "Marketing automation"],
  "Advanced Certified ScrumMaster (A-CSM)": ["Scrum Alliance", "Advanced scrum"],
  "AIIMS INI CET": ["AIIMS", "AIIMS PG entrance"],
  "Akamai Certified Professional": ["nn Database", ""],
  "Alibaba Cloud Certified Professional": ["Alibaba", "Alibaba Cloud"],
  "Alteryx Designer Core Certification": ["Alteryx", "Data preparation"],
  "Android Certified Application Developer": ["Android ATC", "Android apps"],
  "Ansible Certified Specialist": ["Red Hat", "Configuration management"],
  "ANSYS Certified Professional": ["ANSYS", "FEA simulation"],
  "Apache Cassandra Certified Professional": ["DataStax", "Cassandra"],
  "Apache Hadoop Certification": ["Hortonworks", "Hadoop"],
  "Appium Mobile Testing Certification": ["Appium", "Mobile testing"],
  "Apple Certified iOS Developer": ["Apple", "iOS development"],
  "ARCore Certified (Google)": ["Google", "ARCore development"],
  "ARKit Certified (Apple)": ["Apple", "iOS AR development"],
  "ASQ Certified Software Quality Engineer": ["ASQ", "Software quality"],
  "Association of Chartered Certified Accountants (ACCA)": ["ACCA", "International accounting"],
  "Autodesk Certified Professional: AutoCAD": ["Autodesk", "AutoCAD"],
  "Autodesk Certified Professional: Civil 3D": ["Autodesk", "Civil engineering"],
  "Autodesk Certified Professional: Inventor": ["Autodesk", "3D mechanical design"],
  "Autodesk Certified Professional: Revit": ["Autodesk", "Revit architecture"],
  "Autodesk Certified User: Fusion 360": ["Autodesk", "3D CAD/CAM"],
  "AWS Certified Advanced Networking - Specialty": ["Amazon Web Services", "AWS Certified Advanced Networking – Specialty Networking specialization"],
  "AWS Certified Cloud Practitioner": ["Amazon Web Services", "Foundational cloud knowledge"],
  "AWS Certified Data Analytics - Specialty": ["Amazon Web Services", "AWS Certified Data Analytics – Specialty Data analytics on AWS"],
  "AWS Certified Database - Specialty": ["Amazon Web Services", "AWS Certified Database – Specialty Database services"],
  "AWS Certified Developer - Associate": ["Amazon Web Services", "AWS Certified Developer – Associate Developing AWS applications"],
  "AWS Certified DevOps Engineer - Professional": ["Amazon Web Services", "AWS Certified DevOps Engineer – Professional CI/CD and automation"],
  "AWS Certified IoT Specialty": ["AWS", "IoT on AWS"],
  "AWS Certified Machine Learning - Specialty": ["Amazon Web Services", "AWS Certified Machine Learning – Specialty ML on AWS"],
  "AWS Certified ML Specialty": ["AWS", "AWS Certified ML – Specialty ML on AWS"],
  "AWS Certified SAP on AWS - Specialty": ["Amazon Web Services", "AWS Certified SAP on AWS – Specialty SAP workloads"],
  "AWS Certified Security - Specialty": ["Amazon Web Services", "AWS Certified Security – Specialty Cloud security specialization"],
  "AWS Certified Solutions Architect - Associate": ["Amazon Web Services", "AWS Certified Solutions Architect – Associate Designing distributed systems"],
  "AWS Certified Solutions Architect - Professional": ["Amazon Web Services", "AWS Certified Solutions Architect – Professional Advanced architecture design"],
  "AWS Certified SysOps Administrator - Associate": ["Amazon Web Services", "AWS Certified SysOps Administrator – Associate Operations and deployment"],
  "Azure AI Engineer (AI-102)": ["Microsoft", "AI on Azure"],
  "Azure Security Engineer (AZ-500)": ["Microsoft", "Azure security"],
  "BLS/ACLS (Life Support)": ["American Heart Association", "Emergency care"],
  "Burp Suite Certified Practitioner": ["PortSwigger", "Security testing"],
  "C Programming Certified Associate (CPA)": ["C++ Institute", "C programming"],
  "C++ Certified Associate Programmer (CPA)": ["C++ Institute", "C++ programming"],
  "C++ Certified Professional Programmer (CPP)": ["C++ Institute", "Advanced C++"],
  "CAIA - Chartered Alternative Investment Analyst": ["CAIA Association", "CAIA – Chartered Alternative Investment Analyst Alternative investments"],
  "Cambridge English Qualifications (FCE, CAE, CPE)": ["Cambridge English", "General English"],
  "CATIA Certified Professional": ["Dassault Systèmes", "Advanced 3D design"],
  "CELI (Italian)": ["Università per Stranieri", "Italian proficiency"],
  "CELTA - Certificate in Teaching English": ["Cambridge", "CELTA – Certificate in Teaching English English teaching"],
  "Certificado de Portugues (Portuguese)": ["CAPLE", "Certificado de Português (Portuguese) Portuguese proficiency"],
  "Certificado de Português (Portuguese)": ["CAPLE", "Portuguese proficiency"],
  "Certified AI Engineer (CAIE)": ["AI Certification Board", "AI engineering"],
  "Certified Associate in Project Management (CAPM)": ["PMI", "Entry level PM"],
  "Certified Bitcoin Professional (CBP)": ["C4", "Bitcoin"],
  "Certified Blockchain Developer": ["Blockchain Council", "(CBD) Blockchain development"],
  "Certified Blockchain Developer (CBD)": ["Blockchain Council", "Blockchain development"],
  "Certified Cloud Security Professional (CCSP)": ["ISC2", "Cloud security"],
  "Certified Computer Examiner (CCE)": ["ISFCE", "Digital forensics"],
  "Certified Cryptocurrency Trader (CCT)": ["Blockchain Council", "Cryptocurrency"],
  "Certified Data Privacy Solutions Engineer (CDPSE)": ["ISACA", "Privacy"],
  "Certified Data Scientist (CDS)": ["DASCA", "Industry standard"],
  "Certified Ethereum Developer": ["ConsenSys", "Ethereum"],
  "Certified Ethical Hacker (CEH)": ["EC-Council", "Ethical hacking"],
  "Certified Health Data Analyst (CHDA)": ["AHIMA", "Health data"],
  "Certified Healthcare Administrator (CHA)": ["ACHCA", "Healthcare admin"],
  "Certified in Cybersecurity (CC)": ["ISC2", "Cybersecurity basics"],
  "Certified in Risk and Information Systems Control (CRISC)": ["ISACA", "Risk management"],
  "Certified Information Security Manager (CISM)": ["ISACA", "Security management"],
  "Certified Information Systems Auditor (CISA)": ["ISACA", "Auditing"],
  "Certified Information Systems Security Professional (CISSP)": ["ISC2", "Security management"],
  "Certified IoT Professional": ["IoT Council", "IoT implementation"],
  "Certified JavaScript Developer (CJD)": ["International Association of JavaScript", "Core JavaScript"],
  "Certified Kubernetes Administrator (CKA)": ["CNCF", "Kubernetes administration"],
  "Certified Kubernetes Application Developer (CKAD)": ["CNCF", "Kubernetes app development"],
  "Certified Kubernetes Security Specialist (CKS)": ["CNCF", "Kubernetes security"],
  "Certified Public Accountant (CPA)": ["AICPA", "US accounting"],
  "Certified Scrum Product Owner (CSPO)": ["Scrum Alliance", "Product ownership"],
  "Certified ScrumMaster (CSM)": ["Scrum Alliance", "Scrum basics"],
  "Certified VR Developer": ["VR Council", "Virtual reality"],
  "CFP (Certified Financial Planner)": ["CFP Board", "CFP – Certified Financial Planner Financial planning"],
  "Chainlink Certified Developer": ["Chainlink", "Oracles"],
  "Chartered Accountant (CA)": ["ICAI", "Indian accounting"],
  "Chartered Financial Analyst (CFA)": ["CFA Institute", "Investment management"],
  "Chef Certified Developer": ["Progress", "Infrastructure automation"],
  "CILS (Italian)": ["Università di Siena", "Italian proficiency"],
  "CIPM - Certificate in Investment Performance": ["CFA Institute", "CIPM – Certificate in Investment Performance Investment performance"],
  "Cisco Certified CyberOps Associate": ["Cisco", "Security operations"],
  "Cisco Certified Design Associate (CCDA)": ["Cisco", "Network design"],
  "Cisco Certified Internetwork Expert (CCIE)": ["Cisco", "Expert level"],
  "Cisco Certified Network Associate (CCNA)": ["Cisco", "Network fundamentals"],
  "Cisco Certified Network Professional (CCNP)": ["Cisco", "Advanced networking"],
  "Cisco DevNet Associate": ["Cisco", "Network automation"],
  "Cisco IoT Certification": ["Cisco", "Industrial IoT"],
  "CISI Certificate": ["CISI", "Securities & investment"],
  "CLA - C Programming Language Certified Associate": ["C++ Institute", "CLA – C Programming Language Certified Associate C basics"],
  "Cloudera Certified Data Analyst": ["Cloudera", "Hadoop ecosystem"],
  "Cloudera Certified Spark Developer": ["Cloudera", "Apache Spark"],
  "CMA - Certified Management Accountant": ["IMA", "CMA – Certified Management Accountant Management accounting"],
  "COBIT 5 Foundation": ["ISACA", "IT governance"],
  "CompTIA Advanced Security Practitioner (CASP+)": ["CompTIA", "Advanced security"],
  "CompTIA Cloud+": ["CompTIA", "Vendor-neutral cloud skills"],
  "CompTIA CYSA+": ["CompTIA", "Cybersecurity analyst"],
  "CompTIA IoT+": ["CompTIA", "IoT fundamentals"],
  "CompTIA Network+": ["CompTIA", "Networking basics"],
  "CompTIA PenTest+": ["CompTIA", "Penetration testing"],
  "CompTIA Security+": ["CompTIA", "Security fundamentals"],
  "COMSOL Certified": ["COMSOL", "Multiphysics simulation"],
  "Couchbase Certified Developer": ["Couchbase", "Couchbase"],
  "Cypress Certification": ["Cypress", "Modern web testing"],
  "DALF/DELF (French)": ["CIEP", "French proficiency"],
  "DASCA Certified Data Scientist": ["DASCA", "Industry standard"],
  "Data Science Council of America (DASCA)": ["DASCA", "Senior data scientist"],
  "Databricks Certified Data Analyst": ["Databricks", "Databricks lakehouse"],
  "Databricks Certified Data Engineer": ["Databricks", "Data engineering"],
  "Datadog Certified Professional": ["Datadog", "Cloud monitoring"],
  "Deep Learning Specialization": ["deeplearning.ai", "Deep learning"],
  "DELE (Spanish)": ["Instituto Cervantes", "Spanish proficiency"],
  "Django Web Framework Certification": ["Django Project", "Python web framework"],
  "Docker Certified Associate (DCA)": ["Docker Inc", "Containerization"],
  "DOEACC Certifications": ["DOEACC", "Computer applications"],
  "Duolingo English Test": ["Duolingo", "Online English test"],
  "DynamoDB Certification": ["AWS", "DynamoDB (coming)"],
  "Dynatrace Certified Associate": ["Dynatrace", "Observability"],
  "Elasticsearch Certified Engineer": ["Elastic", "Elasticsearch"],
  "Emergency Medical Technician (EMT)": ["NREMT", "Emergency care"],
  "Epicor Certified Professional": ["Epicor", "Epicor ERP"],
  "F5 Certified BIG-IP Administrator": ["F5", "Application delivery"],
  "Flutter Certified Developer": ["Google", "Flutter framework"],
  "FMGE (Foreign Medical Graduate Exam)": ["NBE India", "Foreign medical graduate"],
  "freeCodeCamp Responsive Web Design": ["freeCodeCamp", "HTML/CSS"],
  "FRM (Financial Risk Manager)": ["GARP", "FRM – Financial Risk Manager Risk management"],
  "Full Stack Open": ["University of Helsinki", "Modern web dev"],
  "Full-Stack Web Developer Nanodegree": ["Udacity", "Full stack"],
  "GIAC Certified Forensic Analyst (GCFA)": ["GIAC/SANS", "Forensic analysis"],
  "GIAC Information Security Fundamentals": ["GIAC/SANS", "Security fundamentals"],
  "GIAC Penetration Tester (GPEN)": ["GIAC/SANS", "Pentesting"],
  "GIAC Security Essentials (GSEC)": ["GIAC/SANS", "Security administration"],
  "GitHub Actions Certification": ["GitHub", "GitHub automation"],
  "GitLab Certified Professional": ["GitLab", "GitLab CI/CD"],
  "Go (Golang) Certified Developer": ["The Go Community", "Go programming"],
  "Goethe-Zertifikat (German)": ["Goethe-Institut", "German proficiency"],
  "Google Ads Certification": ["Google", "Google Ads"],
  "Google Analytics Individual Qualification": ["Google", "Analytics"],
  "Google Angular Certification": ["Google", "Angular framework"],
  "Google Associate Android Developer": ["Google", "Android development"],
  "Google Associate Cloud Engineer": ["Google", "Cloud engineering fundamentals"],
  "Google Cloud Database Engineer": ["Google", "Database management"],
  "Google Cloud DevOps Engineer": ["Google", "GCP DevOps"],
  "Google Cloud Digital Leader": ["Google", "Cloud basics"],
  "Google Data Analytics": ["Google", "Professional Data analytics"],
  "Google Data Analytics Certificate": ["Google", "Data analytics basics"],
  "Google Data Analytics Professional": ["Google", "Data analytics"],
  "Google Digital Marketing & E-commerce": ["Google/Coursera", "Digital marketing"],
  "Google Display & Video 360 Certification": ["Google", "Display advertising"],
  "Google Looker Business Intelligence": ["Google", "BI and analytics"],
  "Google Professional Android Developer": ["Google", "Advanced Android"],
  "Google Professional Cloud Architect": ["Google", "Cloud architecture"],
  "Google Professional Cloud Developer": ["Google", "Developing on GCP"],
  "Google Professional Cloud Network Engineer": ["Google", "Networking"],
  "Google Professional Cloud Security Engineer": ["Google", "Security"],
  "Google Professional Collaboration Engineer": ["Google", "Collaboration tools"],
  "Google Professional Data Engineer": ["Google", "Data engineering"],
  "Google Professional ML Engineer": ["Google", "Machine learning"],
  "Google Quantum AI Certification": ["Google", "Quantum computing"],
  "Google Search Ads 360 Certification": ["Google", "Search ads"],
  "Google Shopping Ads Certification": ["Google", "Shopping campaigns"],
  "Google Tag Manager Certification": ["Google", "Tag management"],
  "Google UX Design Professional": ["Google", "UX + frontend"],
  "HashiCorp Certified Consul Associate": ["HashiCorp", "Service mesh"],
  "HashiCorp Certified Vault Associate": ["HashiCorp", "Secrets management"],
  "HashiCorp Certified: Terraform Associate": ["HashiCorp", "Infrastructure as Code"],
  "HP UFT (QTP) Certification": ["Micro Focus", "Functional testing"],
  "HSK (Chinese)": ["Hanban", "Chinese proficiency"],
  "Huawei Certified Network Associate (HCNA)": ["Huawei", "Huawei networking"],
  "Huawei Certified Network Professional (HCNP)": ["Huawei", "Advanced Huawei"],
  "HubSpot Content Marketing": ["HubSpot", "Certification Content strategy"],
  "HubSpot Content Marketing Certification": ["HubSpot", "Content strategy"],
  "HubSpot Email Marketing Certification": ["HubSpot", "Email campaigns"],
  "HubSpot Inbound Marketing Certification": ["HubSpot", "Inbound marketing"],
  "HubSpot SEO Certification": ["HubSpot", "Search optimization"],
  "Hugging Face NLP": ["Hugging Face", "Certification NLP and transformers"],
  "Hugging Face NLP Certification": ["Hugging Face", "NLP and transformers"],
  "Hyperledger Certified Developer": ["Linux Foundation", "Hyperledger"],
  "IBM Back-End Developer": ["IBM", "Backend development"],
  "IBM Data Science Professional": ["IBM/Coursera", "Data science"],
  "IBM Db2 Database Administrator": ["IBM", "Db2 administration"],
  "IBM Full Stack Developer": ["IBM", "Full stack development"],
  "IBM Full Stack Software Developer": ["IBM/Coursera", "Cloud + web"],
  "IBM Quantum Developer Certification": ["IBM", "Qiskit"],
  "ICAgile Certified Professional (ICP)": ["ICAgile", "Agile fundamentals"],
  "IELTS (International English Language Testing System)": ["IDP/Cambridge", "English proficiency"],
  "IGNOU Certifications": ["IGNOU", "Distance education"],
  "Indian Statistical Institute (ISI) Certifications": ["ISI", "Statistics"],
  "Infor Certified Application Specialist": ["Infor", "Infor ERP"],
  "Ionic Certified Developer": ["Ionic", "Hybrid mobile apps"],
  "iOS App Development Certification": ["Stanford (Coursera)", "iOS apps"],
  "IPMA Level A/B/C/D": ["IPMA", "International PM"],
  "iSQI Certified Agile Tester": ["iSQI", "Agile testing"],
  "ISTQB Advanced Technical Test Analyst": ["ISTQB", "Technical testing"],
  "ISTQB Advanced Test Analyst": ["ISTQB", "Test analysis"],
  "ISTQB Advanced Test Manager": ["ISTQB", "Test management"],
  "ISTQB Certified Tester Foundation Level": ["ISTQB", "Testing fundamentals"],
  "ISTQB Expert Level": ["ISTQB", "Expert testing"],
  "ISTQB Security Test Certification": ["ISTQB", "Security testing"],
  "ITIL 4 Foundation": ["AXELOS", "IT service management"],
  "ITIL 4 Managing Professional": ["AXELOS", "Advanced ITIL"],
  "ITIL 4 Strategic Leader": ["AXELOS", "ITIL strategy"],
  "Jenkins Certified Engineer": ["CloudBees", "CI/CD pipelines"],
  "JLPT (Japanese)": ["Japan Foundation", "Japanese proficiency"],
  "JMeter Certified Professional": ["Apache", "Performance testing"],
  "Juniper Networks Certified Associate (JNCIA)": ["Juniper", "Juniper networking"],
  "Juniper Networks Certified Professional (JNCIP)": ["Juniper", "Advanced Juniper"],
  "Kotlin Certification": ["JetBrains/Google", "Kotlin for Android"],
  "Kotlin Certified Developer": ["JetBrains/Google", "Android development"],
  "Laravel Certified Developer": ["Laravel", "PHP framework"],
  "Lean Six Sigma Black Belt": ["ASQ/IAF", "Advanced process improvement"],
  "Lean Six Sigma Green Belt": ["ASQ/IAF", "Process improvement"],
  "LinkedIn Marketing Labs Certification": ["LinkedIn", "LinkedIn marketing"],
  "LoadRunner Certified Professional": ["Micro Focus", "Load testing"],
  "Machine Learning Engineer Nanodegree": ["Udacity", "ML engineering"],
  "Mailchimp Certified": ["Mailchimp", "Email marketing"],
  "Marketo Certified Expert": ["Adobe", "Marketing automation"],
  "MATLAB Certified Associate": ["MathWorks", "MATLAB programming"],
  "MATLAB Certified Professional": ["MathWorks", "Advanced MATLAB"],
  "MCAT (Medical College Admission Test)": ["AAMC", "Medical entrance US"],
  "Medical Billing Certification": ["NHA", "(CBCS) Medical billing"],
  "Medical Billing Certification (CBCS)": ["NHA", "Medical billing"],
  "Medical Coding Certification (CPC)": ["AAPC", "Medical coding"],
  "Medical Laboratory Technician (MLT)": ["ASCP", "Lab technology"],
  "Meta Back-End Developer (Coursera)": ["Meta", "Backend fundamentals"],
  "Meta Back-End Developer Professional": ["Meta/Coursera", "Node.js, Django"],
  "Meta Backend Developer": ["Meta/Coursera", "Meta Back-End Developer Professional Node.js, Django"],
  "Meta Certified Digital Marketing Associate": ["Meta", "Facebook/Instagram"],
  "Meta Certified Media Planning Professional": ["Meta", "Media planning"],
  "Meta Certified Social Media Marketer": ["Meta", "Social media"],
  "Meta Front-End Developer (Coursera)": ["Meta", "Frontend fundamentals"],
  "Meta Front-End Developer Professional": ["Meta/Coursera", "React, HTML, CSS, JS"],
  "Meta Full-Stack Developer": ["Meta", "React + Django"],
  "Meta React Native Developer": ["Meta", "Cross-platform mobile"],
  "Microsoft .NET Developer (AZ-204)": ["Microsoft", "NET development"],
  "Microsoft ASP.NET MVC Certification": ["Microsoft", "Web apps with .NET"],
  "Microsoft Azure Administrator (AZ-104)": ["Microsoft", "Managing Azure resources"],
  "Microsoft Azure AI Engineer (AI-102)": ["Microsoft", "AI solutions"],
  "Microsoft Azure Data Engineer (DP-203)": ["Microsoft", "Data engineering"],
  "Microsoft Azure Data Scientist (DP-100)": ["Microsoft", "Data science"],
  "Microsoft Azure Database Admin (DP-300)": ["Microsoft", "Database administration"],
  "Microsoft Azure Developer (AZ-204)": ["Microsoft", "Developing Azure solutions"],
  "Microsoft Azure DevOps Engineer (AZ-400)": ["Microsoft", "DevOps practices"],
  "Microsoft Azure Fundamentals (AZ-900)": ["Microsoft", "Cloud concepts basics"],
  "Microsoft Azure IoT Developer (AZ-220)": ["Microsoft", "Azure IoT"],
  "Microsoft Azure Quantum Certification": ["Microsoft", "Azure Quantum"],
  "Microsoft Azure Security Engineer (AZ-500)": ["Microsoft", "Security management"],
  "Microsoft Azure Solutions Architect (AZ-305)": ["Microsoft", "Architecture design"],
  "Microsoft Azure Virtual Desktop (AZ-140)": ["Microsoft", "Virtual desktop management"],
  "Microsoft Certified: C# Fundamentals": ["Microsoft", "C# basics"],
  "Microsoft Data Scientist (DP-100)": ["Microsoft", "Azure data science"],
  "Microsoft Data Scientist Associate (DP-100)": ["Microsoft", "Azure data science"],
  "Microsoft Dynamics 365 Finance (MB-310)": ["Microsoft", "D365 Finance"],
  "Microsoft Dynamics 365 Fundamentals (MB-910)": ["Microsoft", "D365 basics"],
  "Microsoft Dynamics 365 Marketing (MB-220)": ["Microsoft", "D365 Marketing"],
  "Microsoft Dynamics 365 Sales (MB-210)": ["Microsoft", "D365 Sales"],
  "Microsoft Power Platform Fundamentals (PL-900)": ["Microsoft", "Power Platform"],
  "Microsoft Python Certification (98-381)": ["Microsoft", "Python programming"],
  "Microsoft SQL Server Database Administrator": ["Microsoft", "SQL Server DBA"],
  "MongoDB Certified Data Analyst": ["MongoDB", "NoSQL analytics"],
  "MongoDB Certified DBA Associate": ["MongoDB", "MongoDB administration"],
  "MongoDB Certified Developer Associate": ["MongoDB", "MongoDB development"],
  "Moz SEO Essentials Certification": ["Moz", "SEO fundamentals"],
  "MRCP (Member of Royal College of Physicians)": ["RCP UK", "UK physician"],
  "MySQL Database Administrator": ["Oracle", "MySQL DBA"],
  "MySQL Developer Certification": ["Oracle", "MySQL development"],
  "National Institute of Electronics & IT (NIELIT)": ["NIELIT", "Electronics & IT"],
  "Natural Language Processing Specialization": ["deeplearning.ai", "NLP"],
  "NCLEX-RN (Nursing)": ["NCSBN", "US nursing license"],
  "NEET PG (National Eligibility Entrance Test)": ["NBE India", "PG medical entrance"],
  "New Relic Certified": ["New Relic", "APM and observability"],
  "NIELIT Certifications (CCC, O Level, A Level)": ["NIELIT, India", "IT skills"],
  "NISM Certifications": ["NISM (India)", "Indian securities market"],
  "Node.js Certified Developer": ["OpenJS Foundation", "Node.js development"],
  "Nursing Officer Exam": ["AIIMS/ESIC", "Nursing recruitment"],
  "NVIDIA Certified: Computer Vision": ["NVIDIA", "Computer vision"],
  "NVIDIA DLI Certifications": ["NVIDIA", "GPU-accelerated AI"],
  "Odoo Certified Professional": ["Odoo", "Odoo ERP"],
  "Offensive Security Certified Professional (OSCP)": ["Offensive Security", "Penetration testing"],
  "Offensive Security Web Expert (OSWE)": ["Offensive Security", "Web app pentesting"],
  "OpenAI Developer Certification": ["OpenAI", "GPT and LLMs"],
  "Oracle Certified Associate Java SE Programmer (OCA)": ["Oracle", "Java fundamentals"],
  "Oracle Certified Master Java SE": ["Oracle", "Master level Java"],
  "Oracle Certified Professional Java EE": ["Oracle", "Enterprise Java"],
  "Oracle Certified Professional Java SE Programmer (OCP)": ["Oracle", "Advanced Java"],
  "Oracle Cloud ERP": ["Oracle", "Certification Oracle Cloud ERP"],
  "Oracle Cloud ERP Certification": ["Oracle", "Oracle Cloud ERP"],
  "Oracle Cloud Infrastructure Certified": ["Oracle", "OCI fundamentals"],
  "Oracle Database Administration Certified Professional": ["Oracle", "Oracle DBA"],
  "Oracle Database SQL Certified Associate": ["Oracle", "Oracle SQL"],
  "Oracle E-Business Suite Certification": ["Oracle", "Oracle EBS"],
  "Oracle Financials Certification": ["Oracle", "Oracle EBS finance"],
  "Oracle JD Edwards Certification": ["Oracle", "JDE"],
  "Oracle NetSuite Certification": ["Oracle", "NetSuite"],
  "Oracle PeopleSoft Certification": ["Oracle", "PeopleSoft"],
  "Palo Alto Networks Certified": ["Palo Alto", "Network security"],
  "PCAP - Certified Associate Python Programmer": ["Python Institute", "PCAP – Certified Associate Python Programmer Intermediate Python"],
  "PCED - Certified Entry-Level Data Scientist": ["Python Institute", "PCED – Certified Entry-Level Data Scientist Data science with Python"],
  "PCEP - Certified Entry-Level Python Programmer": ["Python Institute", "PCEP – Certified Entry-Level Python Programmer Python basics"],
  "PCPP - Certified Professional Python Programmer": ["Python Institute", "PCPP – Certified Professional Python Programmer Advanced Python"],
  "PGIMER Chandigarh Entrance": ["PGIMER", "PGIMER exam"],
  "Pharmacy Technician Certification (PTCB)": ["PTCB", "Pharmacy tech"],
  "PHP Certified Developer": ["Zend", "PHP programming"],
  "Pinterest Ads Certification": ["Pinterest", "Pinterest marketing"],
  "PLAB (Professional & Linguistic Assessment Board)": ["GMC UK", "UK medical license"],
  "PMKVY - Pradhan Mantri Kaushal Vikas Yojana": ["Government of India", "PMKVY – Pradhan Mantri Kaushal Vikas Yojana Skill development"],
  "PostgreSQL Certified Professional": ["PostgreSQL Global", "PostgreSQL"],
  "Power BI Data Analyst (PL-300)": ["Microsoft", "Power BI"],
  "PRINCE2 Foundation": ["AXELOS", "Project governance"],
  "PRINCE2 Practitioner": ["AXELOS", "Advanced PRINCE2"],
  "PRM - Professional Risk Manager": ["PRMIA", "PRM – Professional Risk Manager Risk management"],
  "Professional Scrum Master (PSM I/II/III)": ["Scrum.org", "Scrum mastery"],
  "Project Management Professional (PMP)": ["PMI", "Project management"],
  "Prometheus Certified Associate": ["CNCF", "Monitoring"],
  "PTC Creo Certified Professional": ["PTC", "Creo parametric"],
  "PTE Academic": ["Pearson", "Academic English"],
  "Puppet Certified Professional": ["Puppet", "Infrastructure automation"],
  "QuickBooks Certified User": ["Intuit", "QuickBooks"],
  "R Language Certified": ["R Consortium", "Statistical programming"],
  "Radiology Technologist Certification": ["ARRT", "Radiology"],
  "Red Hat Certified Architect": ["Red Hat", "OpenShift and cloud"],
  "Redis Certified Developer": ["Redis Labs", "Redis"],
  "Registered Pharmacist (India)": ["PCI", "Indian pharmacy"],
  "Ruby Association Certified": ["Ruby Association", "Ruby Programmer Ruby programming"],
  "Ruby Association Certified Ruby Programmer": ["Ruby Association", "Ruby programming"],
  "Ruby on Rails Certification": ["Ruby Community", "Rails framework"],
  "Rust Certified Programmer": ["Rust Foundation", "Rust systems programming"],
  "SAFe Agilist (SA)": ["Scaled Agile", "Enterprise agile"],
  "SAFe Practitioner (SP)": ["Scaled Agile", "SAFe implementation"],
  "SAP Certified Application Associate - BW": ["SAP", "SAP Certified Application Associate – BW SAP Business Warehouse"],
  "SAP Certified Application Associate - Finance (FI)": ["SAP", "SAP Certified Application Associate – Finance (FI) SAP Finance"],
  "SAP Certified Application Associate - HR": ["SAP", "SAP Certified Application Associate – HR SAP Human Resources"],
  "SAP Certified Application Associate - MM": ["SAP", "SAP Certified Application Associate – MM SAP Materials Management"],
  "SAP Certified Application Associate - PP": ["SAP", "SAP Certified Application Associate – PP SAP Production Planning"],
  "SAP Certified Application Associate - Sales (SD)": ["SAP", "SAP Certified Application Associate – Sales (SD) SAP Sales"],
  "SAP Certified Associate - SAP S/4HANA": ["SAP", "SAP Certified Associate – SAP S/4HANA SAP basics"],
  "SAP Certified Development Associate - Fiori": ["SAP", "SAP Certified Development Associate – Fiori SAP Fiori/UI"],
  "SAP Certified Technology Associate - ABAP": ["SAP", "SAP Certified Technology Associate – ABAP SAP ABAP programming"],
  "SAP Finance (FI) Certification": ["SAP", "SAP financials"],
  "SAS Certified Base Programmer": ["SAS", "SAS programming"],
  "SAS Certified Data Scientist": ["SAS", "SAS data science"],
  "Scala Certified Programmer": ["Lightbend", "Scala programming"],
  "SEBI Certification": ["SEBI", "Indian markets"],
  "Selenium WebDriver Certified": ["Selenium", "Web automation"],
  "SEMrush SEO Toolkit Certification": ["SEMrush", "SEO tools"],
  "Siemens NX Certified": ["Siemens", "NX design"],
  "Simulink Certified": ["MathWorks", "Model-based design"],
  "Six Sigma in Healthcare": ["ASQ", "Process improvement"],
  "Skill India Certificate": ["Ministry of Skill Development", "Government skills"],
  "Snapchat Certified": ["Snapchat", "Snapchat ads"],
  "Solana Certified Developer": ["Solana", "Solana blockchain"],
  "SOLIDWORKS Certified Associate (CSWA)": ["Dassault Systèmes", "Entry SolidWorks"],
  "SOLIDWORKS Certified Professional (CSWP)": ["Dassault Systèmes", "SolidWorks"],
  "Splunk Certified Power User": ["Splunk", "Log analysis"],
  "Spring Professional Certification": ["VMware", "Spring framework"],
  "SSC (Staff Selection Commission) Certifications": ["SSC", "Government recruitment"],
  "Stanford AI Professional Program": ["Stanford", "Advanced AI"],
  "Swift Certified Developer": ["Apple", "iOS/macOS development"],
  "Tableau Certified Data Analyst": ["Salesforce", "Advanced analytics"],
  "Tableau Desktop Specialist": ["Salesforce", "Data visualization"],
  "Tally Certified Professional": ["Tally Solutions", "Tally accounting"],
  "TensorFlow Computer Vision": ["Google", "Image recognition"],
  "TensorFlow Developer Certificate": ["Google", "TensorFlow skills"],
  "TESOL Certification": ["TESOL International", "Teaching English"],
  "Test Manager Certification": ["BCS/ISEB", "Test management"],
  "TestComplete Certified Professional": ["SmartBear", "Test automation"],
  "TOEFL (Test of English as a Foreign Language)": ["ETS", "Academic English"],
  "TOEIC (Test of English for International Communication)": ["ETS", "Business English"],
  "TOPIC (Korean)": ["NIIED", "Korean proficiency"],
  "TORFL (Russian)": ["Pushkin Institute", "Russian proficiency"],
  "Twitter Ads Certification": ["Twitter/X", "Twitter advertising"],
  "UI/UX Design Certification": ["Nielsen Norman Group", "User experience design"],
  "Unity Certified Developer": ["Unity Technologies", "AR/VR development"],
  "Unreal Engine Certified": ["Epic Games", "Game/VR development"],
  "USMLE (United States Medical Licensing)": ["USMLE/FSMB", "US medical license"],
  "VMware Certified Professional (VCP)": ["VMware", "Virtualization"],
  "Vue.js Certified Developer": ["Vue.js Community", "Vue.js development"],
  "W3C Front-End Web Developer": ["W3C", "Web standards"],
  "Xamarin Certified Developer": ["Microsoft", "NET mobile dev"],
  "Yoast SEO Certification": ["Yoast", "WordPress SEO"],
  "Zoho Books Certification": ["Zoho", "Zoho accounting"],
};

export const getEnrichment = (name) => ENRICHMENT[name] || ["", ""];